### ISSUE TITLE
PUG task usage help

### ISSUE THREAD

**Issue by vstrelianyi** [khalidhoffman/pug-php-filter#1]
Hi, thx for the useful module! Trying to implement it in my workflow, but getting errors.
Could you pls advise how it can be used in a pug gulp task like this one : 

gulp.task('pug', function buildHTML() {
	return gulp.src( pugSourcePathPages )
       .pipe(pug({ 
        }))
       .pipe(htmlbeautify({	
	 indentSize: 2
         }))	
        .pipe(gulp.dest( pugDestPath ))
  .pipe(browserSync.stream({match: '**/*.html'}));
});

Thx for your time.
Regards,
Viktor.

**Comment by yustnip** [comment]
For example:

```js
pugPHPFilter = require( 'pug-php-filter' )

gulp.task( 'pug', function() {
    return gulp.src( './pug/*.pug' )
        .pipe( pug( { filters: { php: pugPHPFilter } } ) )
        ...
} )
```

**Comment by khalidhoffman** [comment]
Thank you @yustnip. I'm going to close this issue. I've also added a test to ensure this works.

**Comment by vstrelianyi** [comment]
thx!
